import { Documentation, ProjectStructure, APIEndpoint } from '../types';

export class DocumentationComposer {
  compose(structure: ProjectStructure, endpoints: APIEndpoint[], aiAnalysis: string): string {
    return `# ${structure.name}

${aiAnalysis}

---

## 📋 Project Overview

**Languages:** ${structure.languages.join(', ')}  
**Frameworks:** ${structure.frameworks.join(', ')}

## 🛠️ Tech Stack

${structure.frameworks.map(f => `- ${f}`).join('\n')}
${Object.keys(structure.dependencies).slice(0, 10).map(d => `- ${d}`).join('\n')}

## 📁 Folder Structure

\`\`\`
${this.generateTree(structure.files)}
\`\`\`

## 🚀 Setup & Installation

1. Clone the repository
2. Install dependencies:
   \`\`\`bash
   npm install
   \`\`\`
3. Set up environment variables (see below)
4. Run the development server:
   \`\`\`bash
   npm run dev
   \`\`\`

## 🔐 Environment Variables

${this.extractEnvVars(structure)}

## 📡 API Endpoints

${this.formatEndpoints(endpoints)}

## ⚠️ Error Handling

Refer to the codebase for specific error handling implementations.

## 📝 Assumptions

- Standard project structure conventions followed
- Environment variables follow .env.example if present
- API endpoints extracted from code analysis

---

*Generated by Documentation Generator Agent*
`;
  }
  
  private generateTree(files: any[]): string {
    const tree = new Map<string, any>();
    
    files.slice(0, 20).forEach(f => {
      const parts = f.path.split('/');
      tree.set(parts[0], true);
    });
    
    return [...tree.keys()].map(k => `├── ${k}/`).join('\n');
  }
  
  private extractEnvVars(structure: ProjectStructure): string {
    if (structure.keyFiles.envExample) {
      const lines = structure.keyFiles.envExample.split('\n');
      return lines.filter(l => l.includes('=')).map(l => `- \`${l.split('=')[0]}\``).join('\n');
    }
    return '- No environment variables detected';
  }
  
  private formatEndpoints(endpoints: APIEndpoint[]): string {
    if (!endpoints.length) return 'No API endpoints detected.';
    
    return endpoints.map(e => `
### ${e.method} ${e.path}

${e.description || 'No description available'}

**Request:**
\`\`\`json
${JSON.stringify(e.requestBody || {}, null, 2)}
\`\`\`

**Response:**
\`\`\`json
${JSON.stringify(e.responses || {}, null, 2)}
\`\`\`
`).join('\n');
  }
}
